services:
  pf-db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
      - ./pathfinder/export/sql/eve_universe.sql.zip:/eve_universe.sql.zip
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  pf-redis:
    image: valkey/valkey:8-alpine
    command: ["valkey-server", "/etc/redis/redis.conf"]
    volumes:
      - redis_data:/data
      - ./static/redis/redis.conf:/etc/redis/redis.conf:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"
    restart: always

  pf-socket:
    image: ghcr.io/goryn-clade/pf-websocket:latest
    command: ["--tcpHost", "0.0.0.0"]
    volumes:
      - ./logs:/var/www/html/pathfinder/history/map
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always

  pf:
    container_name: pathfinder
    build:
      context: .
      dockerfile: pathfinder.Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    healthcheck:
      disable: true
    volumes:
      - ./config/pathfinder/config.ini:/var/www/html/pathfinder/app/templateConfig.ini
      - ./config/pathfinder/pathfinder.ini:/var/www/html/pathfinder/app/pathfinder.ini
      - ./config/pathfinder/plugin.ini:/var/www/html/pathfinder/app/plugin.ini
      - ./logs:/var/www/html/pathfinder/history/map
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pf-db
      - pf-redis
      - pf-socket
    restart: always

volumes:
  db_data:
  redis_data:
