memory_limit = 256M
upload_max_filesize = 100M
post_max_size = 108M
max_input_vars = 5000
max_execution_time = 30
html_errors = 0
cgi.force_redirect=0
cgi.fix_pathinfo=1
fastcgi.impersonate=1
fastcgi.logging=0
session.save_handler = redis
session.save_path = "${REDIS_SESSION_PATH}"
session.gc_maxlifetime = 86400
session.cookie_lifetime = 86400
session.cookie_httponly = 1
session.cookie_secure = 0
session.cookie_samesite = Lax
[Date]
date.timezone="UTC"

